[project]
name = "rental-prices-predicction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.0.4",
    "scikit-learn>=1.6.1",
    "xgboost>=3.0.0",
]
